# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: windows-latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '3d68cc84-2fee-45a5-9a2c-27d1429712fc'
    definition: '1258'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/Release/16.2'
    artifactName: 'binaries'
    targetPath: '$(Pipeline.Workspace)\..\Code\Bin\Mixed Platforms\Debug'
- task: DocFxTask@0
  inputs:
    solution: 'docfx.json'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $repoURL =  "https://RWS:$env:GITHUB_TOKEN@github.com/icmoldovan/studio-api-docs"
      git clone --depth 1 $repoURL
      cd studio-api-docs
      git checkout main
      git config --global user.name "imoldovan@sdl.com"
      git config --global user.email "icmoldovan"
      copy-item -path ..\api\ -destination .\ -force -recurse
      git commit -a -m "update api doc"
      git -c http.extraheader="AUTHORIZATION: bearer $env:GITHUB_TOKEN" push
  env: 
    GITHUB_TOKEN: $(GITHUB_TOKEN)
#- task: CreatePullRequest@1
#  inputs:
#    repoType: 'GitHub'
#    githubEndpoint: 'icmoldovan'
#    githubRepository: '$(Build.Repository.Name)'
#    sourceBranch: '$(Build.SourceBranch)'
#    targetBranch: 'main'
#    title: 'test'
